manifest:
  remotes:
    - name: mouseftc
      url-base: https://github.com/ftc/zmk/tree/mouse-ftc
  projects:
    - name: zmk
      remote: mouseftc
      revision: main
      import: app/west.yml
  self:
    path: config
